### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by a14en9** [czarmanu/sentinel_lakeice#5]
Hi,

Great work and thanks for releasing the code. I downloaded the sar_ice data by using "https://polybox.ethz.ch/index.php/s/AjRHiOQhvf0vrku". If I understand correctly, this is preprocessed data. But, I got the following error when training the model. Can you update the preprocessed data, please?

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/0e78abc5-0177-4b54-a7a8-9530d423f991/cv/NEOLab/sentinel_lakeice/models/research/deeplab/datasets/sar_ice/exp_2016_17_regionsils/train_on_train_set/vis/segmentation_results/_2016_09_05_0535_sils.png'

Best wishes

**Comment by czarmanu** [comment]
Due to data copyright reasons, we do not share it.

An example code to download the images of lake Sils from winter 2017-18 (with VV polarisation) is available on: https://code.earthengine.google.com/?scriptPath=users%2Frobertoaguilar%2Flakeice%3Asentinel1. You will need to create a GEE account.

To download several images, run the script: data_scripting/gee_browser.js on the browser once GEE tasks are ready (after running the downloading script).
